export const SanitizerConfig = {
	allowComments: false,
	allowCustomElements: false,
	blockElements: ['iframe', 'frame', 'object', 'embed', 'param'],
	dropElements: ['script', 'link', 'title'],
	dropAttributes: {
		onclick: ['*'],
		onerror: ['*'],
		onload: ['*'],
		onloadstart: ['*'],
		onloadend: ['*'],
		onmouseenter: ['*'],
		onmouseleave: ['*'],
		onmousedown: ['*'],
		onmouseup: ['*'],
		onmousein: ['*'],
		onmouseout: ['*'],
		onpointerenter: ['*'],
		onpointerleave: ['*'],
		onpointerdown: ['*'],
		onpointerup: ['*'],
		onpointerin: ['*'],
		onpointerout: ['*'],
		onkeypress: ['*'],
		onkeydown: ['*'],
		onkeyup: ['*'],
		onwheel: ['*'],
		onscroll: ['*'],
		onsubmit: ['*'],
		onformdata: ['*'],
		oncontextmenu: ['*'],
		ondblclick: ['*'],
		oncut: ['*'],
		oncopy: ['*'],
		onpaste: ['*'],
		oninput: ['*'],
		oninvalid: ['*'],
		onchange: ['*'],
		onbeforeinput: ['*'],
		onfocus: ['*'],
		onblur: ['*'],
	},
};
