/**
 * @SEE https://wicg.github.io/sanitizer-api/#sanitizer-api
 * @SEE https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer
 * @TODO: Figure out how to handle combination of `allow` & `block*` in config
 */
const protectedData = new WeakMap();

export class Sanitizer {
	constructor({
		allowElements,
		blockElements,
		dropElements,
		allowAttributes,
		dropAttributes,
		allowCustomElements,
	} = {}) {
		protectedData.set(this, {
			...allowElements, blockElements, dropElements, allowAttributes, dropAttributes, allowCustomElements,
			...Sanitizer.defaultConfig(),
		});
	}

	sanitize(content) {
		if (typeof content === 'string') {
			const template = document.createElement('template');
			template.innerHTML = content;
			return this.sanitize(template.content);
		} else if (content instanceof DocumentFragment) {
			const {
				allowElements, blockElements, dropElements, allowAttributes,
				/*dropAttributes,*/ allowCustomElements,
			} = this.config();

			if (Array.isArray(allowElements) && allowElements.length !== 0) {
				content.querySelectorAll('*').forEach(el => {
					if (! allowElements.includes(el.tagName.toLowerCase())) {
						el.remove();
					}
				});
			}

			Array.from(content.children).forEach(el => {
				if (blockElements.includes(el.tagName.toLowerCase())) {
					el.remove();
				} else if (! allowCustomElements && (el.tagName.includes('-') || el.hasAttribute('is'))) {
					el.remove();
				}
			});

			content.querySelectorAll('*').forEach(el => {
				const tag = el.tagName.toLowerCase();

				if (dropElements.includes(tag)) {
					el.remove();
				} else {
					for (const { localName: attr, value } of el.attributes) {
						if (! (
							allowAttributes.hasOwnProperty(attr)
							&& (allowAttributes[attr].includes('*') || allowAttributes[attr].includes(tag)))
						) {
							el.removeAttribute(attr);
						} else if (['action', 'href'].includes(attr) && value.strartsWith('javascript:')) {
							el.removeAttribute(attr);
						}
					}
				}
			});

			return content;
		}

	}

	sanitizeToString(str) {
		const container = document.createElement('div');
		container.append(this.sanitize(str));
		return container.innerHTML;
	}

	config() {
		return protectedData.get(this);
	}

	/**
	 * @SEE https://wicg.github.io/sanitizer-api/#default-configuration-object
	 */
	static defaultConfig() {
		return Object.seal({
			allowElements: [
				'a',
				'abbr',
				'acronym',
				'address',
				'area',
				'article',
				'aside',
				'audio',
				'b',
				'bdi',
				'bdo',
				'bgsound',
				'big',
				'blockquote',
				'body',
				'br',
				'button',
				'canvas',
				'caption',
				'center',
				'cite',
				'code',
				'col',
				'colgroup',
				'datalist',
				'dd',
				'del',
				'details',
				'dfn',
				'dialog',
				'dir',
				'div',
				'dl',
				'dt',
				'em',
				'fieldset',
				'figcaption',
				'figure',
				'font',
				'footer',
				'form',
				'h1',
				'h2',
				'h3',
				'h4',
				'h5',
				'h6',
				'head',
				'header',
				'hgroup',
				'hr',
				'html',
				'i',
				'img',
				'input',
				'ins',
				'kbd',
				'keygen',
				'label',
				'layer',
				'legend',
				'li',
				'link',
				'listing',
				'main',
				'map',
				'mark',
				'marquee',
				'menu',
				'meta',
				'meter',
				'nav',
				'nobr',
				'noscript',
				'ol',
				'optgroup',
				'option',
				'output',
				'p',
				'picture',
				'popup',
				'pre',
				'progress',
				'q',
				'rb',
				'rp',
				'rt',
				'rtc',
				'ruby',
				's',
				'samp',
				'section',
				'select',
				'selectmenu',
				'small',
				'source',
				'span',
				'strike',
				'strong',
				// 'style',
				'sub',
				'summary',
				'sup',
				'table',
				'tbody',
				'td',
				'tfoot',
				'th',
				'thead',
				'time',
				'tr',
				'track',
				'tt',
				'u',
				'ul',
				'var',
				'video',
				'wbr',
			],
			blockElements: ['script', 'style', 'link', 'iframe', 'object', 'embed', 'noscript', 'blink'],
			dropElements: ['script', 'style', 'link', 'iframe', 'object', 'embed', 'noscript', 'blink'],
			allowAttributes: {
				'abbr': ['*'],
				'accept': ['*'],
				'accept-charset': ['*'],
				'accesskey': ['*'],
				'action': ['*'],
				'align': ['*'],
				'alink': ['*'],
				'allow': ['*'],
				'allowfullscreen': ['*'],
				'alt': ['*'],
				'anchor': ['*'],
				'archive': ['*'],
				'as': ['*'],
				'async': ['*'],
				'autocapitalize': ['*'],
				'autocomplete': ['*'],
				'autocorrect': ['*'],
				'autofocus': ['*'],
				'autopictureinpicture': ['*'],
				'autoplay': ['*'],
				'axis': ['*'],
				'background': ['*'],
				'behavior': ['*'],
				'bgcolor': ['*'],
				'border': ['*'],
				'bordercolor': ['*'],
				'capture': ['*'],
				'cellpadding': ['*'],
				'cellspacing': ['*'],
				'challenge': ['*'],
				'char': ['*'],
				'charoff': ['*'],
				'charset': ['*'],
				'checked': ['*'],
				'cite': ['*'],
				'class': ['*'],
				'classid': ['*'],
				'clear': ['*'],
				'code': ['*'],
				'codebase': ['*'],
				'codetype': ['*'],
				'color': ['*'],
				'cols': ['*'],
				'colspan': ['*'],
				'compact': ['*'],
				'content': ['*'],
				'contenteditable': ['*'],
				'controls': ['*'],
				'controlslist': ['*'],
				'conversiondestination': ['*'],
				'coords': ['*'],
				'crossorigin': ['*'],
				'csp': ['*'],
				'data': ['*'],
				'datetime': ['*'],
				'declare': ['*'],
				'decoding': ['*'],
				'default': ['*'],
				'defer': ['*'],
				'dir': ['*'],
				'direction': ['*'],
				'dirname': ['*'],
				'disabled': ['*'],
				'disablepictureinpicture': ['*'],
				'disableremoteplayback': ['*'],
				'disallowdocumentaccess': ['*'],
				'download': ['*'],
				'draggable': ['*'],
				'elementtiming': ['*'],
				'enctype': ['*'],
				'end': ['*'],
				'enterkeyhint': ['*'],
				'event': ['*'],
				'exportparts': ['*'],
				'face': ['*'],
				'for': ['*'],
				'form': ['*'],
				'formaction': ['*'],
				'formenctype': ['*'],
				'formmethod': ['*'],
				'formnovalidate': ['*'],
				'formtarget': ['*'],
				'frame': ['*'],
				'frameborder': ['*'],
				'headers': ['*'],
				'height': ['*'],
				'hidden': ['*'],
				'high': ['*'],
				'href': ['*'],
				'hreflang': ['*'],
				'hreftranslate': ['*'],
				'hspace': ['*'],
				'http-equiv': ['*'],
				'id': ['*'],
				'imagesizes': ['*'],
				'imagesrcset': ['*'],
				'importance': ['*'],
				'impressiondata': ['*'],
				'impressionexpiry': ['*'],
				'incremental': ['*'],
				'inert': ['*'],
				'inputmode': ['*'],
				'integrity': ['*'],
				'invisible': ['*'],
				'is': ['*'],
				'ismap': ['*'],
				'keytype': ['*'],
				'kind': ['*'],
				'label': ['*'],
				'lang': ['*'],
				'language': ['*'],
				'latencyhint': ['*'],
				'leftmargin': ['*'],
				'link': ['*'],
				'list': ['*'],
				'loading': ['*'],
				'longdesc': ['*'],
				'loop': ['*'],
				'low': ['*'],
				'lowsrc': ['*'],
				'manifest': ['*'],
				'marginheight': ['*'],
				'marginwidth': ['*'],
				'max': ['*'],
				'maxlength': ['*'],
				'mayscript': ['*'],
				'media': ['*'],
				'method': ['*'],
				'min': ['*'],
				'minlength': ['*'],
				'multiple': ['*'],
				'muted': ['*'],
				'name': ['*'],
				'nohref': ['*'],
				'nomodule': ['*'],
				'nonce': ['*'],
				'noresize': ['*'],
				'noshade': ['*'],
				'novalidate': ['*'],
				'nowrap': ['*'],
				'object': ['*'],
				'open': ['*'],
				'optimum': ['*'],
				'part': ['*'],
				'pattern': ['*'],
				'ping': ['*'],
				'placeholder': ['*'],
				'playsinline': ['*'],
				'policy': ['*'],
				'poster': ['*'],
				'preload': ['*'],
				'pseudo': ['*'],
				'readonly': ['*'],
				'referrerpolicy': ['*'],
				'rel': ['*'],
				'reportingorigin': ['*'],
				'required': ['*'],
				'resources': ['*'],
				'rev': ['*'],
				'reversed': ['*'],
				'role': ['*'],
				'rows': ['*'],
				'rowspan': ['*'],
				'rules': ['*'],
				'sandbox': ['*'],
				'scheme': ['*'],
				'scope': ['*'],
				'scopes': ['*'],
				'scrollamount': ['*'],
				'scrolldelay': ['*'],
				'scrolling': ['*'],
				'select': ['*'],
				'selected': ['*'],
				'shadowroot': ['*'],
				'shadowrootdelegatesfocus': ['*'],
				'shape': ['*'],
				'size': ['*'],
				'sizes': ['*'],
				'slot': ['*'],
				'span': ['*'],
				'spellcheck': ['*'],
				'src': ['*'],
				'srcdoc': ['*'],
				'srclang': ['*'],
				'srcset': ['*'],
				'standby': ['*'],
				'start': ['*'],
				'step': ['*'],
				// 'style': ['*'],
				'summary': ['*'],
				'tabindex': ['*'],
				'target': ['*'],
				'text': ['*'],
				'title': ['*'],
				'topmargin': ['*'],
				'translate': ['*'],
				'truespeed': ['*'],
				'trusttoken': ['*'],
				'type': ['*'],
				'usemap': ['*'],
				'valign': ['*'],
				'value': ['*'],
				'valuetype': ['*'],
				'version': ['*'],
				'virtualkeyboardpolicy': ['*'],
				'vlink': ['*'],
				'vspace': ['*'],
				'webkitdirectory': ['*'],
				'width': ['*'],
				'wrap': ['*'],
			},
			dropAttributes: {
				'onload': ['*'],
				'onerror': ['*'],
				'onclick': ['*'],
				'onkeypress': ['*'],
				'onkeydown': ['*'],
				'onkeyup': ['*'],
				'onmouseenter': ['*'],
				'onmouseleave': ['*'],
				'onmousemove': ['*'],
			},
			allowCustomElements: false,
		});
	}
}
