export const STATES = [{
	'abbr': 'AL',
	'name': 'Alabama',
	'group': 'states'
}, {
	'abbr': 'AK',
	'name': 'Alaska',
	'group': 'states'
}, {
	'abbr': 'AS',
	'name': 'American Samoa',
	'group': 'territories'
}, {
	'abbr': 'AZ',
	'name': 'Arizona',
	'group': 'states'
}, {
	'abbr': 'AR',
	'name': 'Arkansas',
	'group': 'states'
}, {
	'abbr': 'AA',
	'name': 'Armed Forces (AA)',
	'group': 'armedForces'
}, {
	'abbr': 'AE',
	'name': 'Armed Forces (AE)',
	'group': 'armedForces',
}, {
	'abbr': 'AP',
	'name': 'Armed Forces (AP)',
	'group': 'armedForces',
}, {
	'abbr': 'CA',
	'name': 'California',
	'group': 'states'
}, {
	'abbr': 'CO',
	'name': 'Colorado',
	'group': 'states'
}, {
	'abbr': 'CT',
	'name': 'Connecticut',
	'group': 'states'
}, {
	'abbr': 'DE',
	'name': 'Delaware',
	'group': 'states'
}, {
	'abbr': 'DC',
	'name': 'District of Columbia',
	'group': 'territories',
}, {
	'abbr': 'FL',
	'name': 'Florida',
	'group': 'states'
}, {
	'abbr': 'GA',
	'name': 'Georgia',
	'group': 'states'
}, {
	'abbr': 'GU',
	'name': 'Guam',
	'group': 'territories',
}, {
	'abbr': 'HI',
	'name': 'Hawaii',
	'group': 'states'
}, {
	'abbr': 'ID',
	'name': 'Idaho',
	'group': 'states'
}, {
	'abbr': 'IL',
	'name': 'Illinois',
	'group': 'states'
}, {
	'abbr': 'IN',
	'name': 'Indiana',
	'group': 'states'
}, {
	'abbr': 'IA',
	'name': 'Iowa',
	'group': 'states'
}, {
	'abbr': 'KS',
	'name': 'Kansas',
	'group': 'states'
}, {
	'abbr': 'KY',
	'name': 'Kentucky',
	'group': 'states'
}, {
	'abbr': 'LA',
	'name': 'Louisiana',
	'group': 'states'
}, {
	'abbr': 'ME',
	'name': 'Maine',
	'group': 'states'
}, {
	'abbr': 'MH',
	'name': 'Marshall Islands',
	'group': 'territories',
}, {
	'abbr': 'MD',
	'name': 'Maryland',
	'group': 'states'
}, {
	'abbr': 'MA',
	'name': 'Massachusetts',
	'group': 'states'
}, {
	'abbr': 'MI',
	'name': 'Michigan',
	'group': 'states'
}, {
	'abbr': 'FM',
	'name': 'Micronesia',
	'group': 'territories'
}, {
	'abbr': 'MN',
	'name': 'Minnesota',
	'group': 'states'
}, {
	'abbr': 'MS',
	'name': 'Mississippi',
	'group': 'states'
}, {
	'abbr': 'MO',
	'name': 'Missouri',
	'group': 'states'
}, {
	'abbr': 'MT',
	'name': 'Montana',
	'group': 'states'
}, {
	'abbr': 'NE',
	'name': 'Nebraska',
	'group': 'states'
}, {
	'abbr': 'NV',
	'name': 'Nevada',
	'group': 'states'
}, {
	'abbr': 'NH',
	'name': 'New Hampshire',
	'group': 'states'
}, {
	'abbr': 'NJ',
	'name': 'New Jersey',
	'group': 'states'
}, {
	'abbr': 'NM',
	'name': 'New Mexico',
	'group': 'states'
}, {
	'abbr': 'NY',
	'name': 'New York',
	'group': 'states'
}, {
	'abbr': 'NC',
	'name': 'North Carolina',
	'group': 'states'
}, {
	'abbr': 'ND',
	'name': 'North Dakota',
	'group': 'states'
}, {
	'abbr': 'MP',
	'name': 'Northern Mariana Islands',
	'group': 'territories'
}, {
	'abbr': 'OH',
	'name': 'Ohio',
	'group': 'states'
}, {
	'abbr': 'OK',
	'name': 'Oklahoma',
	'group': 'states'
}, {
	'abbr': 'OR',
	'name': 'Oregon',
	'group': 'states'
}, {
	'abbr': 'PW',
	'name': 'Palau',
	'group': 'territories',
}, {
	'abbr': 'PA',
	'name': 'Pennsylvania',
	'group': 'states'
}, {
	'abbr': 'PR',
	'name': 'Puerto Rico',
	'group': 'territories'
}, {
	'abbr': 'RI',
	'name': 'Rhode Island',
	'group': 'states'
}, {
	'abbr': 'SC',
	'name': 'South Carolina',
	'group': 'states'
}, {
	'abbr': 'SD',
	'name': 'South Dakota',
	'group': 'states'
}, {
	'abbr': 'TN',
	'name': 'Tennessee',
	'group': 'states'
}, {
	'abbr': 'TX',
	'name': 'Texas',
	'group': 'states'
}, {
	'abbr': 'UT',
	'name': 'Utah',
	'group': 'states'
}, {
	'abbr': 'VT',
	'name': 'Vermont',
	'group': 'states'
}, {
	'abbr': 'VI',
	'name': 'Virgin Islands',
	'group': 'territories'
}, {
	'abbr': 'VA',
	'name': 'Virginia',
	'group': 'states'
}, {
	'abbr': 'WA',
	'name': 'Washington',
	'group': 'states'
}, {
	'abbr': 'WV',
	'name': 'West Virginia',
	'group': 'states'
}, {
	'abbr': 'WI',
	'name': 'Wisconsin',
	'group': 'states'
}, {
	'abbr': 'WY',
	'name': 'Wyoming',
	'group': 'states'
}];
