export {default as Object} from './classes/Object.js';
export {default as JSON} from './classes/JSON.js';
export {default as String} from './classes/String.js';
export {default as Array} from './classes/Array.js';
export {default as Element} from './classes/Element.js';
export {default as CSS} from './classes/CSS.js';
// export {default as Promise} from './classes/Promise.js';
// export {default as Headers} from './classes/Headers.js';
// export {default as Request} from './classes/Request.js';
// export {default as Response} from './classes/Response.js';
